export const todos = [
  {
    id: 1,
    date: "2023-03-04",
    category: "General",
    completed: false,
    title: "Lorem ipsum 1",
    text: "New task sit amet, consectetur adipiscing elit.",
  },
  {
    id: 2,
    date: "2023-02-07",
    category: "Work",
    completed: true,
    title: "Lorem ipsum 2",
    text: "Another task",
  },
  {
    id: 3,
    date: "2023-02-12",
    category: "Study",
    completed: true,
    title: "Blabla",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 4,
    date: "2023-01-04",
    category: "General",
    completed: false,
    title: "Title 4",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 5,
    date: "2023-02-13",
    category: "Study",
    completed: false,
    title: "Title 5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 6,
    date: "2023-02-04",
    category: "Personal",
    completed: true,
    title: "Lorem ipsum 6",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 7,
    date: "2023-02-08",
    category: "General",
    completed: false,
    title: "Lorem ipsum 7",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    date: "2023-02-03",
    category: "Work",
    completed: true,
    title: "Lorem ipsum 8",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 9,
    date: "2023-01-25",
    category: "Study",
    completed: true,
    title: "Blabla",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 10,
    date: "2023-01-29",
    category: "General",
    completed: false,
    title: "Title 4",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 11,
    date: "2023-01-24",
    category: "Study",
    completed: false,
    title: "Title 5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 12,
    date: "2023-02-02",
    category: "Personal",
    completed: true,
    title: "Lorem ipsum 12",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 13,
    date: "2023-02-02",
    category: "Work",
    completed: true,
    title: "Lorem ipsum 2",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 14,
    date: "2023-03-03",
    category: "Study",
    completed: true,
    title: "Blabla",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 15,
    date: "2023-02-22",
    category: "General",
    completed: false,
    title: "Title 4",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 16,
    date: "2023-02-06",
    category: "Study",
    completed: false,
    title: "Title 5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 17,
    date: "2023-02-02",
    category: "General",
    completed: true,
    title: "Lorem ipsum 6",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 18,
    date: "2023-02-13",
    category: "Personal",
    completed: false,
    title: "Title 4",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 19,
    date: "2023-02-25",
    category: "Study",
    completed: false,
    title: "Title 5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 20,
    date: "2023-02-12",
    category: "General",
    completed: true,
    title: "Lorem ipsum 6",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 21,
    date: "2023-02-04",
    category: "Study",
    completed: false,
    title: "Title 5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 22,
    date: "2023-02-08",
    category: "General",
    completed: true,
    title: "Lorem ipsum 6",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 23,
    date: "2023-03-04",
    category: "Study",
    completed: false,
    title: "Title 5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 24,
    date: "2023-01-23",
    category: "General",
    completed: true,
    title: "Lorem ipsum 6",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];
